### ISSUE TITLE
AWT threading problem

### ISSUE THREAD

**Issue by nicity** [CoatiSoftware/idea-sourcetrail#2]
https://youtrack.jetbrains.com/issue/IDEA-188470

java.lang.IllegalStateException: The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[Sourcetrail plugin TCP listener,6,Idea Thread Group]
    at com.intellij.openapi.ui.DialogWrapper.ensureEventDispatchThread(DialogWrapper.java:2178)
    at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1240)
    at com.intellij.openapi.ui.Messages$MessageDialog._init(Messages.java:1425)
    at com.intellij.openapi.ui.Messages$MessageDialog.<init>(Messages.java:1386)
    at com.intellij.openapi.ui.Messages.showDialog(Messages.java:270)
    at com.intellij.openapi.ui.Messages.showDialog(Messages.java:283)
    at com.intellij.openapi.ui.Messages.showDialog(Messages.java:294)
    at com.intellij.openapi.ui.Messages.showMessageDialog(Messages.java:342)
    at io.sourcetrail.idea.Ping.send(Ping.java:31)
    at io.sourcetrail.idea.TcpListener.run(TcpListener.java:49)

**Comment by mlangkabel** [comment]
@nicity, thank you for relaying the info to us. The release 0.4.8 should fix the issue.
